services:
  saturn:
    image: midianok/saturn:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CONNECTION_STRING: ${CONNECTION_STRING}
      IMAGE_MANIPULATION_SERVICE_URL: ${IMAGE_MANIPULATION_SERVICE_URL}
      OperationOptions__CountOperationEnabled: ${OperationOptions__CountOperationEnabled}
      OperationOptions__ShowChatLinkOperationEnabled: ${OperationOptions__ShowChatLinkOperationEnabled}
    depends_on:
      - db
      - image-manipulation-service

  image-manipulation-service:
    build: .
    image: midianok/image-manipulation-service:latest
    restart: always
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ASPNETCORE_URLS: "http://*:80"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local